mysql:
        host: 127.0.0.1
        port: ****
        username: root
        password: ******
        database: ****

emqx:
        username: user
        password: ******
        topic: /Agriculture/#
        broker: 127.0.0.1
        port: ****
